#define TIME_TO_LOCK_UNLOCK_DOORS 300
#define TIME_TO_STOP_MOTORS 1000
#define TIME_TO_MOTORS_CLOSE_UP_DOORS 100 // Dovotchik
#define TIME_TO_CHANGE_MOTORS_SPEED 10000  // should be more then TIME_TO_WAIT_DOOR_EACH_OTHER
#define TIME_TO_RELAY_SWITCH 100
#define TIME_TO_WAIT_DOOR_EACH_OTHER 5000
#define TIME_TO_SWITCH_ON_INTERIOR_LAMP 60000
#define TIME_TO_TOGGLE_SIGNAL_LAMP 1000
#define TIME_TO_COMPLETE_UNLOCKING_DOORS 1000 // should be more then TIME_TO_LOCK_UNLOCK_DOORS + TIME_TO_RELAY_SWITCH
#define TIME_TO_COMPLETE_STOP_DOORS 1000 // should be more then TIME_TO_MOTORS_CLOSE_UP_DOORS

#define KEY_1_CODE 1716305
#define KEY_2_CODE 4670289
#define KEY_3_CODE 2

#define USE_MOTOR_REVOLUTION_COUNTERS true
#define NUMBER_OF_MOTOR_REVOLUTIONS_BEFORE_TO_SPEED_UP 30 // should be moe then NUMBER_OF_RIGHT_MOTOR_REVOLUTIONS_AFTER_START_CLOSE_LEFT_DOOR + NUMBER_OF_LEFT_MOTOR_REVOLUTIONS_AFTER_START_OPEN_RIGHT_DOOR
#define NUMBER_OF_MOTOR_REVOLUTIONS_AFTER_TO_SPEED_DOWN 100
#define NUMBER_OF_RIGHT_MOTOR_REVOLUTIONS_AFTER_START_CLOSE_LEFT_DOOR 10
#define NUMBER_OF_LEFT_MOTOR_REVOLUTIONS_AFTER_START_OPEN_RIGHT_DOOR 10
